auto_scale_lr = dict(base_batch_size=16, enable=False)
backend_args = None
data_root = '../NEU-171K/products/'
dataset_type = 'CocoDataset'
default_hooks = dict(
    checkpoint=dict(interval=1, type='CheckpointHook'),
    logger=dict(interval=50, type='LoggerHook'),
    param_scheduler=dict(type='ParamSchedulerHook'),
    sampler_seed=dict(type='DistSamplerSeedHook'),
    timer=dict(type='IterTimerHook'),
    visualization=dict(type='DetVisualizationHook'))
default_scope = 'mmdet'
env_cfg = dict(
    cudnn_benchmark=False,
    dist_cfg=dict(backend='nccl'),
    mp_cfg=dict(mp_start_method='fork', opencv_num_threads=0))
launcher = 'none'
load_from = None
log_level = 'INFO'
log_processor = dict(by_epoch=True, type='LogProcessor', window_size=50)
model = dict(
    backbone=dict(
        depth=50,
        frozen_stages=1,
        init_cfg=dict(checkpoint='torchvision://resnet50', type='Pretrained'),
        norm_cfg=dict(requires_grad=True, type='BN'),
        norm_eval=True,
        num_stages=4,
        out_indices=(
            0,
            1,
            2,
            3,
        ),
        style='pytorch',
        type='ResNet'),
    bbox_head=dict(
        anchor_generator=dict(
            octave_base_scale=8,
            ratios=[
                1.0,
            ],
            scales_per_octave=1,
            strides=[
                8,
                16,
                32,
                64,
                128,
            ],
            type='AnchorGenerator'),
        feat_channels=256,
        in_channels=256,
        loss_bbox=dict(loss_weight=2.0, type='GIoULoss'),
        loss_cls=dict(
            beta=2.0,
            loss_weight=1.0,
            type='QualityFocalLoss',
            use_sigmoid=True),
        loss_dfl=dict(loss_weight=0.25, type='DistributionFocalLoss'),
        num_classes=121,
        reg_max=16,
        stacked_convs=4,
        type='GFLHead'),
    data_preprocessor=dict(
        bgr_to_rgb=True,
        mean=[
            123.675,
            116.28,
            103.53,
        ],
        pad_size_divisor=32,
        std=[
            58.395,
            57.12,
            57.375,
        ],
        type='DetDataPreprocessor'),
    neck=dict(
        add_extra_convs='on_output',
        in_channels=[
            256,
            512,
            1024,
            2048,
        ],
        num_outs=5,
        out_channels=256,
        start_level=1,
        type='FPN'),
    test_cfg=dict(
        max_per_img=100,
        min_bbox_size=0,
        nms=dict(iou_threshold=0.6, type='nms'),
        nms_pre=1000,
        score_thr=0.05),
    train_cfg=dict(
        allowed_border=-1,
        assigner=dict(topk=9, type='ATSSAssigner'),
        debug=False,
        pos_weight=-1),
    type='GFL')
optim_wrapper = dict(
    optimizer=dict(lr=0.01, momentum=0.9, type='SGD', weight_decay=0.0001),
    type='OptimWrapper')
param_scheduler = [
    dict(
        begin=0, by_epoch=False, end=500, start_factor=0.001, type='LinearLR'),
    dict(
        begin=0,
        by_epoch=True,
        end=50,
        gamma=0.1,
        milestones=[
            8,
            11,
        ],
        type='MultiStepLR'),
]
resume = False
test_cfg = dict(type='TestLoop')
test_dataloader = dict(
    batch_size=12,
    dataset=dict(
        ann_file='test/instances_rp_test.json',
        backend_args=None,
        data_prefix=dict(img='test/images/'),
        data_root='../NEU-171K/products/',
        metainfo=dict(
            classes=(
                'Tissue_Paper Thin',
                'Toiletries_Saky Toothpaste',
                'Beverage_Nongfu Spring Jasmine Tea',
                'Toiletries_Toothbrush',
                'Alcohol_Snow Beer',
                'Stationery_Glue Stick',
                'Instant Drink_Huangwei Black Sesame Paste',
                "Snacks_Lay's Cucumber Flavor Potato Chips",
                'Condiment_Monosodium Glutamate (MSG)',
                'Condiment_China Salt',
                'Instant Noodles_Pickled Mustard Beef Noodles',
                'Dessert_Oreo Mini Cocoa Pastry',
                'Toiletries_Liushen Soap',
                'Puffed Food_Onion Chips (Blue)',
                'Canned Food_Luncheon Meat',
                'Beverage_Coffee',
                'Condiment_Orange Tree Refined Sea Salt',
                'Milk_Wangzai Milk',
                'Toiletries_Safeguard Soap',
                'Candy_Skittles Jar',
                'Condiment_Xizaiji Oil and Vinegar Dressing',
                'Condiment_Heinz Tomato Ketchup',
                'Instant Noodles_Baixiang Golden Soup Fatty Beef',
                'Canned Food_Wahaha Xylitol Porridge',
                'Canned Food_Ribbonfish Canned',
                'Instant Drink_Youlemei Wheat Flavor',
                'Toiletries_Lux Soap',
                'Instant Noodles_Uni-President Seafood Ramen',
                'Dried Fruit_Plums',
                'Chewing Gum_Plummed Tablets',
                'Tissue_Tissue',
                'Tissue_Boxed Tissue',
                'Candy_Strawberry Candy',
                'Condiment_White Vinegar',
                "Chocolate_Hershey's Chocolate",
                'Chocolate_Q Beans',
                'Beverage_Six Walnuts',
                'Toiletries_Hand Soap',
                'Candy_Charcoal Roasted Coffee Candy',
                'Gum_Five5 Watermelon Flavor Gum',
                'Dried Fruit_Yitian Nuts',
                'Dessert_Chocolate Wafer',
                'Beverage_Nongfu Spring Mineral Water',
                'Dried Fruit_Zhenglin Sunflower Seeds',
                'Canned Food_Wahaha Longan and Lotus Seed Porridge',
                'Dried Fruit_Liuliumei Green',
                'Dried Snacks_Laojuechu Spicy Peanuts',
                "Snack_Food_Lay's Potato Chips (Bagged)",
                'Puffed Food_Want Want Mini Crisps',
                'Canned Food_Xiduoduo Goji Berry Porridge',
                'Candy_Want Want QQ Gummies',
                'Candy_Want Want Milk Candy',
                'Dried Fruit_Crystal Lemon Slices',
                'Dried Fruit_Hawthorn Blocks',
                'Dried Fruit_Liuliumei Powder',
                'Milk_Soy Milk',
                'Milk_Anmuxi',
                'Instant Noodles_Haidilao Tomato Beef Soup Noodles',
                'Snacks_Haoyouqu Potato Chips Bagged',
                'Candy_Animal Gummies',
                'Seasoning_Li Salt',
                'Milk_Coffee Milk',
                'Chewing Gum_Doublemint Lozenges',
                'Dessert_Chip Delight Soft Cookies',
                'Condiment_Qishen Horseradish',
                'Chocolate_Kinder Chocolate',
                'Beverage_Red Bull',
                'Candy_Skittles Bag',
                'Stationery_Scissors',
                'Dessert_Quduo Mini Cookies',
                'Instant Drink_Nescafé Absolute Deep Black',
                'Canned_Fish Roe Caviar',
                "Puffed Snacks_Lay's Potato Chips Canister",
                'Stationery_Gel Pen',
                'Snacks_Ya Potato',
                'Dried Fruit_Qiaqia Hi Sunflower Seeds',
                'Milk_Mengniu Boxed',
                'Dried Fruit_Strange Flavor Beans',
                'Instant Noodles_Lucky Bear Spicy Sour Powder',
                'Alcohol_Tiger Beer',
                'Dried Fruit_Dried Tangerine Peel',
                'Stationery_Notebook',
                'Chocolate_JiuJiu Dark Chocolate',
                'Personal Care_Shanghai Medicinal Soap',
                'Dried Fruit_Green Peas',
                'Candy_Popping Candy',
                'Dried Fruits_Qiaqia Caramel Melon Seeds',
                'Chocolate_Mylikes',
                'Milk_Wangzai Milk Can',
                'Dried Fruit_Castanets',
                'Stationery_Eraser',
                'Instant Noodles_Spicy Beef Noodles',
                'Chocolate_Mylikes Coconut Flavor',
                'Dessert_Oreo Chocolate Flavor',
                'Instant Drink_Yo-lo-mei',
                'Chewing Gum_Mentos',
                'Dried Fruit_Yangmei',
                'Snacks_Friend Fun Steak Flavored Chips',
                'Condiment_Qishen Black Pepper Powder',
                'Alcohol_Snow Beer Blue',
                'Candy_Orion Orange Candy',
                'Instant Noodles_Braised Beef Noodles',
                'Instant Noodles_Tomato Egg Beef Noodles',
                'Instant Noodles_Shrimp Fish Cake Noodles',
                'Dessert_Chocolate Pie',
                'Drink_Coconut Tree Coconut Juice',
                'Drink_Sprite',
                'Drink_Coca-Cola',
                'Drink_Suntory Oolong Tea',
                'Drink_Enen Soda Water',
                'Dessert_Oreo Original Flavor',
                'Canned_Fresh Stewed Tremella by Xiduoduo',
                'Dessert_Q Ti',
                'Chocolate_Green Chocolate',
                'Tissue_Banbu Facial Tissue',
                "Snacks_Lay's Barbecue Flavored Chips",
                'Milk_AD Calcium Milk',
                'Beverage_Dalian Soda',
                'Personal Care_Tissues',
                'Stationery_Correction Tape',
                'Dry Fruits_Mustard Peanuts',
            )),
        pipeline=[
            dict(backend_args=None, type='LoadImageFromFile'),
            dict(keep_ratio=True, scale=(
                1333,
                800,
            ), type='Resize'),
            dict(type='LoadAnnotations', with_bbox=True),
            dict(
                meta_keys=(
                    'img_id',
                    'img_path',
                    'ori_shape',
                    'img_shape',
                    'scale_factor',
                ),
                type='PackDetInputs'),
        ],
        test_mode=True,
        type='CocoDataset'),
    drop_last=False,
    num_workers=12,
    persistent_workers=True,
    sampler=dict(shuffle=False, type='DefaultSampler'))
test_evaluator = dict(
    ann_file=
    '../NEU-171K/products/test/instances_rp_test.json',
    backend_args=None,
    format_only=False,
    metric='bbox',
    type='CocoMetric')
test_pipeline = [
    dict(backend_args=None, type='LoadImageFromFile'),
    dict(keep_ratio=True, scale=(
        1333,
        800,
    ), type='Resize'),
    dict(type='LoadAnnotations', with_bbox=True),
    dict(
        meta_keys=(
            'img_id',
            'img_path',
            'ori_shape',
            'img_shape',
            'scale_factor',
        ),
        type='PackDetInputs'),
]
train_cfg = dict(max_epochs=12, type='EpochBasedTrainLoop', val_interval=1)
train_dataloader = dict(
    batch_sampler=dict(type='AspectRatioBatchSampler'),
    batch_size=12,
    dataset=dict(
        ann_file='train/instances_rp_train.json',
        backend_args=None,
        data_prefix=dict(img='train/images/'),
        data_root='../NEU-171K/products/',
        filter_cfg=dict(filter_empty_gt=True, min_size=32),
        metainfo=dict(
            classes=(
                'Tissue_Paper Thin',
                'Toiletries_Saky Toothpaste',
                'Beverage_Nongfu Spring Jasmine Tea',
                'Toiletries_Toothbrush',
                'Alcohol_Snow Beer',
                'Stationery_Glue Stick',
                'Instant Drink_Huangwei Black Sesame Paste',
                "Snacks_Lay's Cucumber Flavor Potato Chips",
                'Condiment_Monosodium Glutamate (MSG)',
                'Condiment_China Salt',
                'Instant Noodles_Pickled Mustard Beef Noodles',
                'Dessert_Oreo Mini Cocoa Pastry',
                'Toiletries_Liushen Soap',
                'Puffed Food_Onion Chips (Blue)',
                'Canned Food_Luncheon Meat',
                'Beverage_Coffee',
                'Condiment_Orange Tree Refined Sea Salt',
                'Milk_Wangzai Milk',
                'Toiletries_Safeguard Soap',
                'Candy_Skittles Jar',
                'Condiment_Xizaiji Oil and Vinegar Dressing',
                'Condiment_Heinz Tomato Ketchup',
                'Instant Noodles_Baixiang Golden Soup Fatty Beef',
                'Canned Food_Wahaha Xylitol Porridge',
                'Canned Food_Ribbonfish Canned',
                'Instant Drink_Youlemei Wheat Flavor',
                'Toiletries_Lux Soap',
                'Instant Noodles_Uni-President Seafood Ramen',
                'Dried Fruit_Plums',
                'Chewing Gum_Plummed Tablets',
                'Tissue_Tissue',
                'Tissue_Boxed Tissue',
                'Candy_Strawberry Candy',
                'Condiment_White Vinegar',
                "Chocolate_Hershey's Chocolate",
                'Chocolate_Q Beans',
                'Beverage_Six Walnuts',
                'Toiletries_Hand Soap',
                'Candy_Charcoal Roasted Coffee Candy',
                'Gum_Five5 Watermelon Flavor Gum',
                'Dried Fruit_Yitian Nuts',
                'Dessert_Chocolate Wafer',
                'Beverage_Nongfu Spring Mineral Water',
                'Dried Fruit_Zhenglin Sunflower Seeds',
                'Canned Food_Wahaha Longan and Lotus Seed Porridge',
                'Dried Fruit_Liuliumei Green',
                'Dried Snacks_Laojuechu Spicy Peanuts',
                "Snack_Food_Lay's Potato Chips (Bagged)",
                'Puffed Food_Want Want Mini Crisps',
                'Canned Food_Xiduoduo Goji Berry Porridge',
                'Candy_Want Want QQ Gummies',
                'Candy_Want Want Milk Candy',
                'Dried Fruit_Crystal Lemon Slices',
                'Dried Fruit_Hawthorn Blocks',
                'Dried Fruit_Liuliumei Powder',
                'Milk_Soy Milk',
                'Milk_Anmuxi',
                'Instant Noodles_Haidilao Tomato Beef Soup Noodles',
                'Snacks_Haoyouqu Potato Chips Bagged',
                'Candy_Animal Gummies',
                'Seasoning_Li Salt',
                'Milk_Coffee Milk',
                'Chewing Gum_Doublemint Lozenges',
                'Dessert_Chip Delight Soft Cookies',
                'Condiment_Qishen Horseradish',
                'Chocolate_Kinder Chocolate',
                'Beverage_Red Bull',
                'Candy_Skittles Bag',
                'Stationery_Scissors',
                'Dessert_Quduo Mini Cookies',
                'Instant Drink_Nescafé Absolute Deep Black',
                'Canned_Fish Roe Caviar',
                "Puffed Snacks_Lay's Potato Chips Canister",
                'Stationery_Gel Pen',
                'Snacks_Ya Potato',
                'Dried Fruit_Qiaqia Hi Sunflower Seeds',
                'Milk_Mengniu Boxed',
                'Dried Fruit_Strange Flavor Beans',
                'Instant Noodles_Lucky Bear Spicy Sour Powder',
                'Alcohol_Tiger Beer',
                'Dried Fruit_Dried Tangerine Peel',
                'Stationery_Notebook',
                'Chocolate_JiuJiu Dark Chocolate',
                'Personal Care_Shanghai Medicinal Soap',
                'Dried Fruit_Green Peas',
                'Candy_Popping Candy',
                'Dried Fruits_Qiaqia Caramel Melon Seeds',
                'Chocolate_Mylikes',
                'Milk_Wangzai Milk Can',
                'Dried Fruit_Castanets',
                'Stationery_Eraser',
                'Instant Noodles_Spicy Beef Noodles',
                'Chocolate_Mylikes Coconut Flavor',
                'Dessert_Oreo Chocolate Flavor',
                'Instant Drink_Yo-lo-mei',
                'Chewing Gum_Mentos',
                'Dried Fruit_Yangmei',
                'Snacks_Friend Fun Steak Flavored Chips',
                'Condiment_Qishen Black Pepper Powder',
                'Alcohol_Snow Beer Blue',
                'Candy_Orion Orange Candy',
                'Instant Noodles_Braised Beef Noodles',
                'Instant Noodles_Tomato Egg Beef Noodles',
                'Instant Noodles_Shrimp Fish Cake Noodles',
                'Dessert_Chocolate Pie',
                'Drink_Coconut Tree Coconut Juice',
                'Drink_Sprite',
                'Drink_Coca-Cola',
                'Drink_Suntory Oolong Tea',
                'Drink_Enen Soda Water',
                'Dessert_Oreo Original Flavor',
                'Canned_Fresh Stewed Tremella by Xiduoduo',
                'Dessert_Q Ti',
                'Chocolate_Green Chocolate',
                'Tissue_Banbu Facial Tissue',
                "Snacks_Lay's Barbecue Flavored Chips",
                'Milk_AD Calcium Milk',
                'Beverage_Dalian Soda',
                'Personal Care_Tissues',
                'Stationery_Correction Tape',
                'Dry Fruits_Mustard Peanuts',
            )),
        pipeline=[
            dict(backend_args=None, type='LoadImageFromFile'),
            dict(type='LoadAnnotations', with_bbox=True),
            dict(keep_ratio=True, scale=(
                1333,
                800,
            ), type='Resize'),
            dict(prob=0.5, type='RandomFlip'),
            dict(type='PackDetInputs'),
        ],
        type='CocoDataset'),
    num_workers=12,
    persistent_workers=True,
    sampler=dict(shuffle=True, type='DefaultSampler'))
train_pipeline = [
    dict(backend_args=None, type='LoadImageFromFile'),
    dict(type='LoadAnnotations', with_bbox=True),
    dict(keep_ratio=True, scale=(
        1333,
        800,
    ), type='Resize'),
    dict(prob=0.5, type='RandomFlip'),
    dict(type='PackDetInputs'),
]
val_cfg = dict(type='ValLoop')
val_dataloader = dict(
    batch_size=12,
    dataset=dict(
        ann_file='val/instances_rp_val.json',
        backend_args=None,
        data_prefix=dict(img='val/images/'),
        data_root='../NEU-171K/products/',
        metainfo=dict(
            classes=(
                'Tissue_Paper Thin',
                'Toiletries_Saky Toothpaste',
                'Beverage_Nongfu Spring Jasmine Tea',
                'Toiletries_Toothbrush',
                'Alcohol_Snow Beer',
                'Stationery_Glue Stick',
                'Instant Drink_Huangwei Black Sesame Paste',
                "Snacks_Lay's Cucumber Flavor Potato Chips",
                'Condiment_Monosodium Glutamate (MSG)',
                'Condiment_China Salt',
                'Instant Noodles_Pickled Mustard Beef Noodles',
                'Dessert_Oreo Mini Cocoa Pastry',
                'Toiletries_Liushen Soap',
                'Puffed Food_Onion Chips (Blue)',
                'Canned Food_Luncheon Meat',
                'Beverage_Coffee',
                'Condiment_Orange Tree Refined Sea Salt',
                'Milk_Wangzai Milk',
                'Toiletries_Safeguard Soap',
                'Candy_Skittles Jar',
                'Condiment_Xizaiji Oil and Vinegar Dressing',
                'Condiment_Heinz Tomato Ketchup',
                'Instant Noodles_Baixiang Golden Soup Fatty Beef',
                'Canned Food_Wahaha Xylitol Porridge',
                'Canned Food_Ribbonfish Canned',
                'Instant Drink_Youlemei Wheat Flavor',
                'Toiletries_Lux Soap',
                'Instant Noodles_Uni-President Seafood Ramen',
                'Dried Fruit_Plums',
                'Chewing Gum_Plummed Tablets',
                'Tissue_Tissue',
                'Tissue_Boxed Tissue',
                'Candy_Strawberry Candy',
                'Condiment_White Vinegar',
                "Chocolate_Hershey's Chocolate",
                'Chocolate_Q Beans',
                'Beverage_Six Walnuts',
                'Toiletries_Hand Soap',
                'Candy_Charcoal Roasted Coffee Candy',
                'Gum_Five5 Watermelon Flavor Gum',
                'Dried Fruit_Yitian Nuts',
                'Dessert_Chocolate Wafer',
                'Beverage_Nongfu Spring Mineral Water',
                'Dried Fruit_Zhenglin Sunflower Seeds',
                'Canned Food_Wahaha Longan and Lotus Seed Porridge',
                'Dried Fruit_Liuliumei Green',
                'Dried Snacks_Laojuechu Spicy Peanuts',
                "Snack_Food_Lay's Potato Chips (Bagged)",
                'Puffed Food_Want Want Mini Crisps',
                'Canned Food_Xiduoduo Goji Berry Porridge',
                'Candy_Want Want QQ Gummies',
                'Candy_Want Want Milk Candy',
                'Dried Fruit_Crystal Lemon Slices',
                'Dried Fruit_Hawthorn Blocks',
                'Dried Fruit_Liuliumei Powder',
                'Milk_Soy Milk',
                'Milk_Anmuxi',
                'Instant Noodles_Haidilao Tomato Beef Soup Noodles',
                'Snacks_Haoyouqu Potato Chips Bagged',
                'Candy_Animal Gummies',
                'Seasoning_Li Salt',
                'Milk_Coffee Milk',
                'Chewing Gum_Doublemint Lozenges',
                'Dessert_Chip Delight Soft Cookies',
                'Condiment_Qishen Horseradish',
                'Chocolate_Kinder Chocolate',
                'Beverage_Red Bull',
                'Candy_Skittles Bag',
                'Stationery_Scissors',
                'Dessert_Quduo Mini Cookies',
                'Instant Drink_Nescafé Absolute Deep Black',
                'Canned_Fish Roe Caviar',
                "Puffed Snacks_Lay's Potato Chips Canister",
                'Stationery_Gel Pen',
                'Snacks_Ya Potato',
                'Dried Fruit_Qiaqia Hi Sunflower Seeds',
                'Milk_Mengniu Boxed',
                'Dried Fruit_Strange Flavor Beans',
                'Instant Noodles_Lucky Bear Spicy Sour Powder',
                'Alcohol_Tiger Beer',
                'Dried Fruit_Dried Tangerine Peel',
                'Stationery_Notebook',
                'Chocolate_JiuJiu Dark Chocolate',
                'Personal Care_Shanghai Medicinal Soap',
                'Dried Fruit_Green Peas',
                'Candy_Popping Candy',
                'Dried Fruits_Qiaqia Caramel Melon Seeds',
                'Chocolate_Mylikes',
                'Milk_Wangzai Milk Can',
                'Dried Fruit_Castanets',
                'Stationery_Eraser',
                'Instant Noodles_Spicy Beef Noodles',
                'Chocolate_Mylikes Coconut Flavor',
                'Dessert_Oreo Chocolate Flavor',
                'Instant Drink_Yo-lo-mei',
                'Chewing Gum_Mentos',
                'Dried Fruit_Yangmei',
                'Snacks_Friend Fun Steak Flavored Chips',
                'Condiment_Qishen Black Pepper Powder',
                'Alcohol_Snow Beer Blue',
                'Candy_Orion Orange Candy',
                'Instant Noodles_Braised Beef Noodles',
                'Instant Noodles_Tomato Egg Beef Noodles',
                'Instant Noodles_Shrimp Fish Cake Noodles',
                'Dessert_Chocolate Pie',
                'Drink_Coconut Tree Coconut Juice',
                'Drink_Sprite',
                'Drink_Coca-Cola',
                'Drink_Suntory Oolong Tea',
                'Drink_Enen Soda Water',
                'Dessert_Oreo Original Flavor',
                'Canned_Fresh Stewed Tremella by Xiduoduo',
                'Dessert_Q Ti',
                'Chocolate_Green Chocolate',
                'Tissue_Banbu Facial Tissue',
                "Snacks_Lay's Barbecue Flavored Chips",
                'Milk_AD Calcium Milk',
                'Beverage_Dalian Soda',
                'Personal Care_Tissues',
                'Stationery_Correction Tape',
                'Dry Fruits_Mustard Peanuts',
            )),
        pipeline=[
            dict(backend_args=None, type='LoadImageFromFile'),
            dict(keep_ratio=True, scale=(
                1333,
                800,
            ), type='Resize'),
            dict(type='LoadAnnotations', with_bbox=True),
            dict(
                meta_keys=(
                    'img_id',
                    'img_path',
                    'ori_shape',
                    'img_shape',
                    'scale_factor',
                ),
                type='PackDetInputs'),
        ],
        test_mode=True,
        type='CocoDataset'),
    drop_last=False,
    num_workers=12,
    persistent_workers=True,
    sampler=dict(shuffle=False, type='DefaultSampler'))
val_evaluator = dict(
    ann_file=
    '../NEU-171K/products/val/instances_rp_val.json',
    backend_args=None,
    format_only=False,
    metric='bbox',
    type='CocoMetric')
vis_backends = [
    dict(type='LocalVisBackend'),
]
visualizer = dict(
    name='visualizer',
    type='DetLocalVisualizer',
    vis_backends=[
        dict(type='LocalVisBackend'),
    ])
work_dir = 'GFLGood'
